### ISSUE TITLE
Add CRUD for orders and order-lines

### ISSUE THREAD

**Issue by jnorton65** [azurestandard/website#20]
Via IRC:

> wking - jacob: as an alternative to checkout-side stuff, filling in the CrUD for orders and order-lines should be reasonably straightforward, and then heuscher could wire into those new endpoints while he works over the category shopping

**Comment by jnorton65** [comment]
After much wailing and gnashing of teeth, this *should* be ready. I'm having (yet more) DB issues (Not isolated to my changes), but I don't see any problem with my changes. Any chance I could just need to get a newer backup of the production DB?

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 06:42:34PM -0800, Jacob Norton wrote:
> After much wailing and gnashing of teeth, this *should* be
> ready. I'm having (yet more) DB issues (Not isolated to my changes),
> but I don't see any problem with my changes. Any chance I could just
> need to get a newer backup of the production DB?

Sure, I'll start a new snapshot after I finish the current
N2-won't-load-in-the-picking-admin bug. ;)

**Comment by wking** [comment]
Merged—after some fixups and the addition of update and delete endpoints—in 5ca174e9 (Merge branch 'tk/order-orderline-crud', 2015-01-29).
