### ISSUE TITLE
Overlapping portions of the product-detail page

### ISSUE THREAD

**Issue by wking** [azurestandard/website#21]
With Firefox on a netbook monitor (not very wide), I'm getting:

![sc065](https://cloud.githubusercontent.com/assets/209920/5766523/21067614-9cb7-11e4-8037-83297e196b5e.png)

The picture on the left overlaps some of the product name and description, and the list of alternative packaging is also floating on top of the description.

**Comment by heuscher** [comment]
For front-end bugs, a screenshot from [http://supportdetails.com/](support details), will help me out. Specifically, browser, screen resolution, and browser size.

**Comment by wking** [comment]
On Thu, Jan 15, 2015 at 01:14:53PM -0800, heuscher wrote:
> … browser, screen resolution, and browser size.

Operating System: X11 Linux x86_64
Web Browser: Firefox 24.0
Screen Resolution: 1366 x 768
Browser Size: 1366 x 659

**Comment by heuscher** [comment]
Fixed in website@6b3506e
