### ISSUE TITLE
"Shop Azure" menu flickers as mouse moves

### ISSUE THREAD

**Issue by wking** [azurestandard/website#23]
The "Shop Azure" menu is a bit flaky in my Firefox 24.8 and Chromium 39.0.  In both browsers the menu is flickery, but in Firefox the flickering seems slower.  In both it's sometimes hard to browse into the submenues for second-level categories.  @heuscher says a refresh usually fixes it for him, but I haven't been that lucky myself ;).

If it's unusable for you, you can always just click on "Shop Azure" itself and use the category listing to drill down.

**Comment by jnorton65** [comment]
I'm not able to reproduce this with Chromium 39.0, is this fixed?

**Comment by heuscher** [comment]
I haven't noticed the issue in a bit, but I'm not sure if it's been fixed. 

If it occurs again, I'll try to get some more info.

**Comment by shofetim** [comment]
@heuscher I can reproduce it now, which may be enough for you to find and fix it, if not let me know and I'll look take a try at it.

1. Open [Shop Azure](http://azurestandard.github.io/website/#/shop)
2. Using the drop down menu under *Shop Azure* navigate to a category *you have not yet viewed* click to view that category.
3. Attempt to use the menu.
