### ISSUE TITLE
Associate payment methods with orders at checkout time

### ISSUE THREAD

**Issue by wking** [azurestandard/website#26]
So folks can allocate a credit-card for a particular order, or say they'll be using their net-30 or whatever.  @jnorton65 is researching this.

**Comment by shofetim** [comment]
@jnorton65 Order.checkout_payment_type  https://github.com/azurestandard/beehive/blob/master/apps/orders/models.py#L81 is likely what you are after.

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 01:18:35PM -0800, Jordan Schatz wrote:
> @jnorton65 Order.checkout_payment_type
> https://github.com/azurestandard/beehive/blob/master/apps/orders/models.py#L81
> is likely what you are after.

Thanks :).  There's also Order.checkout_payment, which is setup here
[1].  Are credit-card Payments created and associated with orders at
checkout time, but only settled at ship time?  Or are Payments created
at ship-time and settled immediately, with some other model bridging
checkout and shipping?

[1]: https://github.com/azurestandard/beehive/blob/f565bf776c79560ea23d3f52bf45bc4ae3bf0b0b/apps/accounts_receivable/models.py#L78

**Comment by jnorton65** [comment]
So it looks like at checkout [1], the existing order is given a payment type (and the payment is created). After that, during shipping [2], the credit card is charged (if the payment method is a card). From there the Order.checkout_payment is used to determine payment status on the order [3]. However, that's not the only time charging can occur, since accounts receivable can also charge cards [4]. 

[1]  https://github.com/azurestandard/beehive/blob/master/apps/shop/views.py#746
[2]  https://github.com/azurestandard/beehive/blob/master/apps/shipping/views.py#L165
[3]  https://github.com/azurestandard/beehive/blob/master/apps/orders/models.py#L1247
[4]  https://github.com/azurestandard/beehive/blob/master/apps/accounts_receivable/views.py#L24

**Comment by jnorton65** [comment]
So it seems like there should be a payment endpoint, which takes and order and a payment method (plus whatever else a payment needs) that is hit at checkout time

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 10:34:21AM -0700, Jacob Norton wrote:
> So it seems like there should be a payment endpoint, which takes and
> order and a payment method (plus whatever else a payment needs) that
> is hit at checkout time

For checkout, maybe all we need is an order['payment-method'] field
with the ID for the intended payment method?  Then customers can
associate the credit card (or other payment method) they want to use,
and we don't have to add a separate endpoint.

If we wanted to handle card-charging through the API, we would need an
extra endpoint, but I think we can get by without that for the time
being.

**Comment by jnorton65** [comment]
So the Order PUT would create a new payment and add the payment method, and then the shipping app would charge it like normal? If so, the PUT method would need to reject changes after the order has shipped, and accept changes until then, which should be pretty simple

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 11:08:04AM -0700, Jacob Norton wrote:
> So the Order PUT would create a new payment and add the payment
> method, and then the shipping app would charge it like normal? If
> so, the PUT method would need to reject changes after the order has
> shipped, and accept changes until then, which should be pretty
> simple

Yeah, and PUTs that change or remove an existing payment-method
assignment would need to make the appropriate updates as well.

Ideally we'd migrate the database models to more closely reflect this
API (so we don't have to create/edit/delete payments when PUTing
orders), but I'm putting that off until we can deprecate the old
website.

**Comment by wking** [comment]
This is now possible since ab17695 (CheckoutCtrl: PUT order after
selecting payment method and submitting, 2015-04-27) and e0a130b
(CheckoutCtrl: Reset state on PUT failure, 2015-04-27).

**Comment by wking** [comment]
Closing since the association works now.
