### ISSUE TITLE
Cookie-based login

### ISSUE THREAD

**Issue by wking** [azurestandard/website#45]
In 39c79cf86 (SignInCtrl: Remove in favor of the brower's native auth dialog, 2015-02-09), I dropped the sign-in modal because Chromium wasn't returning the cookie in follow-up requeusts (details in the commit message).  Using native basic-auth works fairly well, except:

1. We can't clear those credentials from JavaScript, so there's no way to log out besides having the user manually clear their credentials.
2. We'll want a cookie-based system to preserve state for unauthenticated users when we get around to implementing anonymous carts (although see discussion and Basecamp links in d2c030b93, Add 'Sign In' and 'Sign Out' buttons, 2014-11-29).

So we'd like to restore the sign-in modal and sign-out button, and wire them up in a way that gives us working cookies for all of our supported browsers (there's a list in #22).

**Comment by tompetersjr** [comment]
## Excerpt from Requirements Document

A link in the header will allow a user to login.  The UI for logging in does not yet exist and the visual implementation of the feature is flexible.  Logging in without leaving the page would be preferable.  This could be implemented through a modal dialog or by dropping\scrolling the page header down and putting a login at the top of the page.  The login page should allow the user to sign up for an account if they do not have one.  The sign up link should redirect the user to the get started section that will walk the user through the signup process.

Once a user is logged in we want them to stay logged in 6 months unless they sign out.  Users can sign out by going to the my account page.  The link to sign out exists on the left side of the page.

If a user is not logged in then we want to in-evasively prompt them for a zip code.  This zip code will allow us to deliver accurate pricing to the user.  This prompt would be optional.  If they do not provide a zip code then we will not display customized pricing.  If they do provide a zip code we can show them targeted pricing.  This targeted pricing can wait until phase ii of the site but we want to have it wired up and ready to go by prompting the user for the zip code.  Once a zip code is entered then the prompt will be replaced with text such as “Please visit the home page to learn more about our unique delivery process.”[1].  The implementation of this can be done by showing a notification bar under the bread crumbs on the shopping pages.  This notification would be dismissable by the customer if they choose to dismiss it.

[1] Will need to talk to the marketing department to get better working and any possible linking in this text.

**Comment by wking** [comment]
One more wrinkle on this front is that we might *not* want to return
the semantically-correct 401 error on failure.  I have fuzzy memories
of that causing browsers to pop up their basic-auth dialog to ask the
user to try again, and that's not what we want here.  @MercenaryJosh,
can you check this out and:

a. Confirm that Chromium and Firefox do or don't pop up their native
   basic-auth dialog on invalid login credentials.
b. If they do pop up a basic-auth dialog, adjust the /login
   implementation in azurestandard/beehive to return a 400 error so we
   can handle the login-failed case ourselves in Angular.

**Comment by MercenaryJosh** [comment]
Chrome and Firefox do not display their native basic-auth dialog on receiving a 401 response.

**Comment by wking** [comment]
Fixed with f3bf467 and 8a3eef2.
