### ISSUE TITLE
Login Dialog Cleanup

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/website#50]
The login dialog box needs to be cleaned up a little bit on the UI side.

![screen shot 2015-06-16 at 8 37 28 am](https://cloud.githubusercontent.com/assets/11820955/8187296/084e8318-1404-11e5-9698-702d438b21b6.png)

We should put a little vertical space between the textboxes and make them the full width of the dialog's container.  Right now most email addresses are too long and the textbox scrolls horizontally.  We could also shorten the width of the modal by about 1/4th.  Just noticed the cancel button is hidden.  I think this style has been fixed in another branch.  If not please coordinate with @heuscher to get the cancel button style so that it is not hidden.

You can follow the screenshot below taken from "Get Started" as style guide for the spacing and look and feel of the text boxes.

![screen shot 2015-06-16 at 8 43 00 am](https://cloud.githubusercontent.com/assets/11820955/8187394/5bfc7948-1404-11e5-8732-102d9aaf85f3.png)

**Comment by wking** [comment]
On Tue, Jul 14, 2015 at 04:30:25PM -0700, MercenaryJosh wrote:
> Closed #50 via 27e579caa154001881fcf7c3dca10cd1823cf5e0.

That commit handled the spacing and width, but the 'Cancel' button is
still invisible (at least on Firefox) until you mouse over it.

**Comment by wking** [comment]
I'm not sure which commit fixed the cancel styling, but it seems to be better now:

![sign-in](https://cloud.githubusercontent.com/assets/209920/9066804/846525aa-3a8e-11e5-8a68-a3d7dfe0022b.png)
